# 秒/分/時/日/月/曜日
cron:
  cron1: 0 * * * * *

# DBは環境変数から設定 例)DB_USERNAME=username
spring:
  datasource:
    url: jdbc:mysql://localhost/tabelogdb?serverTimezone=JST
    username: ${db.username:username}
    password: ${db.password:password}
    driverClassName: ${db.drivername:driverClassName}
